# Generated by Django 3.1.7 on 2021-03-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichier',
            old_name='nom',
            new_name='title',
        ),
    ]
