# Generated by Django 3.1.7 on 2021-03-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210330_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='title',
            field=models.TextField(),
        ),
    ]
