# Generated by Django 3.1.7 on 2021-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210331_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='texte',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichier',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
