# Generated by Django 3.1.7 on 2021-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_fichier_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='commentaire',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
