# Generated by Django 3.1.7 on 2021-04-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fichier_commentaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichier',
            options={'ordering': ['title']},
        ),
    ]
