# Generated by Django 3.1.7 on 2021-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210402_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='sortie',
            field=models.FileField(default=0, upload_to='sortie'),
            preserve_default=False,
        ),
    ]
