# Generated by Django 3.1.7 on 2021-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fichier_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
