# Generated by Django 3.1.7 on 2021-04-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fichier_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='sortie',
        ),
    ]
