# Generated by Django 3.1.7 on 2021-04-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_fichier_sortie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='sortie',
        ),
    ]
