# Generated by Django 3.1.7 on 2021-04-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210406_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='sortie',
        ),
    ]
