# Generated by Django 3.1.7 on 2021-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210407_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='sorti',
            field=models.ImageField(upload_to='media'),
        ),
    ]
