# Generated by Django 3.1.7 on 2021-04-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210407_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='sorti',
        ),
        migrations.AddField(
            model_name='fichier',
            name='sortie',
            field=models.FileField(default='non', upload_to='media'),
            preserve_default=False,
        ),
    ]
