# Generated by Django 3.1.7 on 2021-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210407_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='sortie',
            field=models.FileField(upload_to='media'),
        ),
    ]
