# Generated by Django 3.1.7 on 2021-04-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210407_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='sortie',
        ),
    ]
