# Generated by Django 3.1.7 on 2021-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_fichier_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='contenu',
            field=models.FileField(upload_to='nouveau'),
        ),
    ]
