# Generated by Django 3.1.7 on 2021-04-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210409_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='commentaire',
        ),
    ]
